import java.util.Properties
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinxSerialization)
    alias(libs.plugins.sqldelight)
}

/**
 * Firebase config is a per-deployment secret and is not in the repository. Applying the plugin
 * without it fails the Android build outright, so it is applied only when the file is actually
 * there: a clone with no credentials still builds, installs and runs — it just never receives a
 * notification. Drop the file downloaded from the Firebase console next to this build script to
 * turn push on.
 */
val googleServicesJson = layout.projectDirectory.file("google-services.json").asFile
if (googleServicesJson.exists()) {
    apply(plugin = libs.plugins.googleServices.get().pluginId)
} else {
    logger.lifecycle("composeApp: no google-services.json — Android push notifications will be inert in this build")
}

/**
 * Version and commit as they were when the binary was built. Read from git here rather than at
 * runtime because no target ships a git checkout alongside the app — the numbers have to be baked
 * into the source.
 */
val appVersionName = "1.0"

fun git(vararg args: String): String? = runCatching {
    val result = providers.exec {
        commandLine("git", *args)
        workingDir = rootDir
    }
    // Non-zero exit (no git, no checkout) throws here and falls through to the null default.
    result.result.get().assertNormalExitValue()
    result.standardOutput.asText.get().trim().ifEmpty { null }
}.getOrNull()

/**
 * Writes BuildInfo.kt into the build directory and wires it into commonMain, so the drawer can show
 * which build it is without any target needing a platform-specific hook.
 */
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    // Captured at configuration time: a task action must not touch the project object.
    val commit = git("rev-parse", "--short", "HEAD") ?: "unknown"
    val dirty = git("status", "--porcelain") != null && git("status", "--porcelain")!!.isNotEmpty()
    val branch = git("rev-parse", "--abbrev-ref", "HEAD") ?: "unknown"
    val version = appVersionName

    inputs.property("commit", commit)
    inputs.property("dirty", dirty)
    inputs.property("branch", branch)
    inputs.property("version", version)
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile.resolve("com/example/app")
        dir.mkdirs()
        dir.resolve("BuildInfo.kt").writeText(
            """
            package com.example.app

            /** Generated by the :composeApp:generateBuildInfo Gradle task. Do not edit. */
            object BuildInfo {
                const val VERSION: String = "$version"
                const val COMMIT: String = "$commit"
                const val BRANCH: String = "$branch"
                const val DIRTY: Boolean = $dirty

                /** What the drawer prints: "1.0 (088db36)", with a * when the tree was dirty. */
                val label: String get() = "${'$'}VERSION (${'$'}COMMIT${'$'}{if (DIRTY) "*" else ""})"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    jvm("desktop")

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
                // Webpack's default of 8080 collides with too much on a dev machine; give the
                // browser build a port of its own.
                devServer = (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                    port = 8081
                }
            }
        }
        binaries.executable()
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        val desktopMain by getting
        val desktopTest by getting

        commonMain.get().kotlin.srcDir(generateBuildInfo)

        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
            implementation(libs.compose.unstyled)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            // Generated Database/Queries classes from the .sq schema below live in commonMain
            // regardless of target; only android/iOS actually open a SQLite driver against them
            // (see LocalCache), but the runtime types they're built on have to resolve everywhere,
            // wasmJs included.
            implementation(libs.sqldelight.runtime)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.okhttp)
            // Push. Compiled in unconditionally so the messaging service is always part of the app;
            // whether it can do anything depends on google-services.json being present at build
            // time (see the plugin block above) and is handled at runtime.
            implementation(project.dependencies.platform(libs.firebase.bom))
            implementation(libs.firebase.messaging)
            implementation(libs.sqldelight.android.driver)
            // Nothing here uses a Fragment. It is declared to raise the version: firebase-messaging
            // drags in androidx.fragment 1.1.0 through play-services-basement, and a FragmentActivity
            // older than 1.3.0 fails to call super.onRequestPermissionsResult(), which breaks
            // registerForActivityResult — the permission launcher in push/Push.android.kt. Lint says
            // so as a *fatal* error, so a release build does not even finish without this line.
            implementation(libs.androidx.fragment)
        }
        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.sqldelight.native.driver)
        }
        wasmJsMain.dependencies {
            implementation(libs.ktor.client.js)
        }
        desktopTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.compose.ui.test)
        }
    }
}

sqldelight {
    databases {
        // Backs LocalCache on android/iOS only (see that file) — a single key/value table, not a
        // real relational schema, so one small database is enough for every cached response.
        create("AppDatabase") {
            packageName.set("com.example.app.data.db")
        }
    }
}

/**
 * Signing material for the Play upload key. Same rule as google-services.json above: it is a
 * per-deployment secret, so nothing about it lives in the repository. Values come from the
 * environment (that is what CI has) or from a gitignored `keystore.properties` next to this build
 * script (that is what a person building a signed binary by hand has). With neither, `release`
 * stays unsigned and still builds — a clone must not need a keystore to compile.
 */
val keystoreProperties = layout.projectDirectory.file("keystore.properties").asFile
    .takeIf { it.exists() }
    ?.let { file -> Properties().apply { file.inputStream().use { load(it) } } }

fun signingValue(env: String, property: String): String? =
    providers.environmentVariable(env).orNull?.ifEmpty { null }
        ?: keystoreProperties?.getProperty(property)?.ifEmpty { null }

val keystorePath = signingValue("ANDROID_KEYSTORE_FILE", "storeFile")

android {
    // Deliberately still the template package, and not the application id below: the manifest names
    // its components relatively (`.MainActivity`, `.push.AgentizMessagingService`) and AGP resolves
    // those against the namespace, so changing it without moving every source file under
    // `cx/m42/agentoz/` would leave the launcher activity pointing at a class that does not exist.
    // The namespace is a compile-time detail — it is not what identifies the app to FCM or to Play.
    namespace = "com.example.app"
    compileSdk = libs.versions.androidCompileSdk.get().toInt()

    defaultConfig {
        // What actually identifies the installation: to Play, and to FCM, whose google-services.json
        // must contain a client with exactly this package name — the Google Services plugin fails
        // the build outright when it does not, rather than leaving push quietly inert.
        // Deliberately *not* the iOS bundle id (`cx.m42.agentoz` in
        // iosApp/Configuration/Config.xcconfig), which belongs to the app already on TestFlight.
        // The two stores never compare the strings, and a Play package cannot be renamed once its
        // app record exists — so this string is chosen when the Play app is created and is fixed
        // from that moment on.
        applicationId = "cx.m42.agentiz"
        minSdk = libs.versions.androidMinSdk.get().toInt()
        targetSdk = libs.versions.androidTargetSdk.get().toInt()
        // Play refuses an upload whose versionCode it has already seen, so the number has to come
        // from something that only ever grows and is not edited by hand: the CI run number
        // (`ANDROID_VERSION_CODE`). A local build keeps 1 — it never reaches Play.
        versionCode = providers.environmentVariable("ANDROID_VERSION_CODE").orNull?.toIntOrNull() ?: 1
        versionName = appVersionName
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    signingConfigs {
        // Declared only when the material is actually there; referencing a signingConfig whose
        // storeFile does not exist fails the build at execution time rather than falling back.
        if (keystorePath != null) {
            create("release") {
                storeFile = file(keystorePath)
                storePassword = signingValue("ANDROID_KEYSTORE_PASSWORD", "storePassword")
                keyAlias = signingValue("ANDROID_KEY_ALIAS", "keyAlias")
                keyPassword = signingValue("ANDROID_KEY_PASSWORD", "keyPassword")
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            // Absent keystore ⇒ an unsigned release artifact, which is exactly what the build
            // produced before this config existed.
            signingConfig = signingConfigs.findByName("release")
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.example.app.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Agentiz"
            packageVersion = "1.0.0"
        }
    }
}
