import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpackConfig

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinxSerialization)
}

/**
 * Version and commit as they were when the binary was built. Read from git here rather than at
 * runtime because no target ships a git checkout alongside the app — the numbers have to be baked
 * into the source.
 */
val appVersionName = "1.0"

fun git(vararg args: String): String? = runCatching {
    val result = providers.exec {
        commandLine("git", *args)
        workingDir = rootDir
    }
    // Non-zero exit (no git, no checkout) throws here and falls through to the null default.
    result.result.get().assertNormalExitValue()
    result.standardOutput.asText.get().trim().ifEmpty { null }
}.getOrNull()

/**
 * Writes BuildInfo.kt into the build directory and wires it into commonMain, so the drawer can show
 * which build it is without any target needing a platform-specific hook.
 */
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildinfo/kotlin")
    // Captured at configuration time: a task action must not touch the project object.
    val commit = git("rev-parse", "--short", "HEAD") ?: "unknown"
    val dirty = git("status", "--porcelain") != null && git("status", "--porcelain")!!.isNotEmpty()
    val branch = git("rev-parse", "--abbrev-ref", "HEAD") ?: "unknown"
    val version = appVersionName

    inputs.property("commit", commit)
    inputs.property("dirty", dirty)
    inputs.property("branch", branch)
    inputs.property("version", version)
    outputs.dir(outputDir)

    doLast {
        val dir = outputDir.get().asFile.resolve("com/example/app")
        dir.mkdirs()
        dir.resolve("BuildInfo.kt").writeText(
            """
            package com.example.app

            /** Generated by the :composeApp:generateBuildInfo Gradle task. Do not edit. */
            object BuildInfo {
                const val VERSION: String = "$version"
                const val COMMIT: String = "$commit"
                const val BRANCH: String = "$branch"
                const val DIRTY: Boolean = $dirty

                /** What the drawer prints: "1.0 (088db36)", with a * when the tree was dirty. */
                val label: String get() = "${'$'}VERSION (${'$'}COMMIT${'$'}{if (DIRTY) "*" else ""})"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    jvm("desktop")

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
                // Webpack's default of 8080 collides with too much on a dev machine; give the
                // browser build a port of its own.
                devServer = (devServer ?: KotlinWebpackConfig.DevServer()).apply {
                    port = 8081
                }
            }
        }
        binaries.executable()
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        val desktopMain by getting
        val desktopTest by getting

        commonMain.get().kotlin.srcDir(generateBuildInfo)

        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
            implementation(libs.compose.unstyled)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.okhttp)
        }
        desktopMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        wasmJsMain.dependencies {
            implementation(libs.ktor.client.js)
        }
        desktopTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.compose.ui.test)
        }
    }
}

android {
    namespace = "com.example.app"
    compileSdk = libs.versions.androidCompileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.example.app"
        minSdk = libs.versions.androidMinSdk.get().toInt()
        targetSdk = libs.versions.androidTargetSdk.get().toInt()
        versionCode = 1
        versionName = appVersionName
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
}

compose.desktop {
    application {
        mainClass = "com.example.app.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Agentiz"
            packageVersion = "1.0.0"
        }
    }
}
